export const CODEBASE_VISUALIZER_ROUTE_BASE = '/__codebase-visualizer'
export const CODEBASE_VISUALIZER_ROUTE =
  `${CODEBASE_VISUALIZER_ROUTE_BASE}/snapshot`
export const CODEBASE_VISUALIZER_LAYOUTS_ROUTE =
  `${CODEBASE_VISUALIZER_ROUTE_BASE}/layouts`
export const CODEBASE_VISUALIZER_PREPROCESSING_ROUTE =
  `${CODEBASE_VISUALIZER_ROUTE_BASE}/preprocessing`
export const CODEBASE_VISUALIZER_PREPROCESSING_SUMMARY_ROUTE =
  `${CODEBASE_VISUALIZER_PREPROCESSING_ROUTE}/summary`
export const CODEBASE_VISUALIZER_PREPROCESSING_EMBEDDINGS_ROUTE =
  `${CODEBASE_VISUALIZER_PREPROCESSING_ROUTE}/embeddings`
export const CODEBASE_VISUALIZER_DRAFTS_ROUTE =
  `${CODEBASE_VISUALIZER_ROUTE_BASE}/drafts`
export const CODEBASE_VISUALIZER_AGENT_ROUTE_BASE =
  `${CODEBASE_VISUALIZER_ROUTE_BASE}/agent`
export const CODEBASE_VISUALIZER_AGENT_SESSION_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_ROUTE_BASE}/session`
export const CODEBASE_VISUALIZER_AGENT_MESSAGE_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_ROUTE_BASE}/message`
export const CODEBASE_VISUALIZER_AGENT_CANCEL_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_ROUTE_BASE}/cancel`
export const CODEBASE_VISUALIZER_AGENT_SETTINGS_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_ROUTE_BASE}/settings`
export const CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE =
  `${CODEBASE_VISUALIZER_AGENT_ROUTE_BASE}/auth`
export const CODEBASE_VISUALIZER_AGENT_AUTH_SESSION_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/session`
export const CODEBASE_VISUALIZER_AGENT_AUTH_LOGIN_START_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/login/start`
export const CODEBASE_VISUALIZER_AGENT_AUTH_COMPLETE_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/complete`
export const CODEBASE_VISUALIZER_AGENT_AUTH_LOGOUT_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/logout`
export const CODEBASE_VISUALIZER_AGENT_AUTH_IMPORT_CODEX_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/import-codex`
export const CODEBASE_VISUALIZER_AGENT_AUTH_CALLBACK_ROUTE =
  `${CODEBASE_VISUALIZER_AGENT_AUTH_ROUTE_BASE}/callback`

export function buildCodebaseVisualizerDraftActionRoute(
  draftId: string,
  action: 'accept' | 'reject',
) {
  return `${CODEBASE_VISUALIZER_DRAFTS_ROUTE}/${encodeURIComponent(draftId)}/${action}`
}
