export const SEMANTICODE_ROUTE_BASE = '/__semanticode'
export const SEMANTICODE_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/snapshot`
export const SEMANTICODE_LAYOUTS_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/layouts`
export const SEMANTICODE_SEMANTIC_LAYOUT_ROUTE =
  `${SEMANTICODE_LAYOUTS_ROUTE}/semantic`
export const SEMANTICODE_LAYOUT_SUGGEST_ROUTE =
  `${SEMANTICODE_LAYOUTS_ROUTE}/suggest`
export const SEMANTICODE_LAYOUT_QUERY_ROUTE =
  `${SEMANTICODE_LAYOUTS_ROUTE}/query`
export const SEMANTICODE_PREPROCESSING_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/preprocessing`
export const SEMANTICODE_SYNC_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/sync`
export const SEMANTICODE_FILE_DIFF_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/file-diff`
export const SEMANTICODE_WORKSPACE_HISTORY_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/workspace-history`
export const SEMANTICODE_UI_PREFERENCES_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/ui-preferences`
export const SEMANTICODE_PREPROCESSING_SUMMARY_ROUTE =
  `${SEMANTICODE_PREPROCESSING_ROUTE}/summary`
export const SEMANTICODE_PREPROCESSING_EMBEDDINGS_ROUTE =
  `${SEMANTICODE_PREPROCESSING_ROUTE}/embeddings`
export const SEMANTICODE_GROUP_PROTOTYPES_ROUTE =
  `${SEMANTICODE_PREPROCESSING_ROUTE}/group-prototypes`
export const SEMANTICODE_DRAFTS_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/drafts`
export const SEMANTICODE_AGENT_ROUTE_BASE =
  `${SEMANTICODE_ROUTE_BASE}/agent`
export const SEMANTICODE_RUNS_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/runs`
export const SEMANTICODE_TELEMETRY_ROUTE_BASE =
  `${SEMANTICODE_ROUTE_BASE}/telemetry`
export const SEMANTICODE_TELEMETRY_OVERVIEW_ROUTE =
  `${SEMANTICODE_TELEMETRY_ROUTE_BASE}/overview`
export const SEMANTICODE_TELEMETRY_HEATMAP_ROUTE =
  `${SEMANTICODE_TELEMETRY_ROUTE_BASE}/heatmap`
export const SEMANTICODE_TELEMETRY_ACTIVITY_ROUTE =
  `${SEMANTICODE_TELEMETRY_ROUTE_BASE}/activity`
export const SEMANTICODE_AGENT_SESSION_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/session`
export const SEMANTICODE_AGENT_SESSIONS_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/sessions`
export const SEMANTICODE_AGENT_CONTROLS_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/controls`
export const SEMANTICODE_AGENT_SESSION_NEW_ROUTE =
  `${SEMANTICODE_AGENT_SESSION_ROUTE}/new`
export const SEMANTICODE_AGENT_SESSION_RESUME_ROUTE =
  `${SEMANTICODE_AGENT_SESSION_ROUTE}/resume`
export const SEMANTICODE_AGENT_SESSION_DELETE_ROUTE =
  `${SEMANTICODE_AGENT_SESSION_ROUTE}/delete`
export const SEMANTICODE_AGENT_MESSAGE_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/message`
export const SEMANTICODE_AGENT_CANCEL_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/cancel`
export const SEMANTICODE_AGENT_THINKING_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/thinking`
export const SEMANTICODE_AGENT_TOOLS_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/tools`
export const SEMANTICODE_AGENT_MODEL_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/model`
export const SEMANTICODE_AGENT_COMPACT_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/compact`
export const SEMANTICODE_AGENT_SETTINGS_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/settings`
export const SEMANTICODE_AGENT_AUTH_ROUTE_BASE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/auth`
export const SEMANTICODE_AGENT_AUTH_SESSION_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/session`
export const SEMANTICODE_AGENT_AUTH_LOGIN_START_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/login/start`
export const SEMANTICODE_AGENT_AUTH_COMPLETE_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/complete`
export const SEMANTICODE_AGENT_AUTH_LOGOUT_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/logout`
export const SEMANTICODE_AGENT_AUTH_IMPORT_CODEX_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/import-codex`
export const SEMANTICODE_AGENT_AUTH_CALLBACK_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/callback`

export function buildSemanticodeDraftActionRoute(
  draftId: string,
  action: 'accept' | 'reject',
) {
  return `${SEMANTICODE_DRAFTS_ROUTE}/${encodeURIComponent(draftId)}/${action}`
}

export function buildSemanticodeRunRoute(runId: string) {
  return `${SEMANTICODE_RUNS_ROUTE}/${encodeURIComponent(runId)}`
}

export function buildSemanticodeRunStopRoute(runId: string) {
  return `${buildSemanticodeRunRoute(runId)}/stop`
}

export function buildSemanticodeRunTimelineRoute(runId: string) {
  return `${buildSemanticodeRunRoute(runId)}/timeline`
}
