export type {
  AutonomousRunDetail,
  AutonomousRunScope,
  AutonomousRunStartRequest,
  AutonomousRunStatus,
  AutonomousRunSummary,
  AutonomousRunLiveFeedEntry,
  AutonomousRunTimelinePoint,
  AutonomousRunTodoSummary,
} from './schema/autonomous'
export type {
  AgentAuthMode,
  AgentBrokerAuthState,
  AgentBrokerSessionSummary,
  AgentCapabilitySet,
  AgentCommandInfo,
  AgentCommandSource,
  AgentControlState,
  AgentEvent,
  AgentFileOperation,
  AgentFileOperationConfidence,
  AgentFileOperationKind,
  AgentFileOperationSource,
  AgentFileOperationStatus,
  AgentMessage,
  AgentMessageBlock,
  AgentModelControlOption,
  AgentModelOption,
  AgentPermissionRequest,
  AgentRunState,
  AgentRuntimeKind,
  AgentSessionListItem,
  AgentSessionSummary,
  AgentSecretStorageKind,
  AgentSettingsInput,
  AgentSettingsState,
  AgentSourceInfo,
  AgentTimelineItem,
  AgentToolControlInfo,
  AgentToolInvocation,
} from './schema/agent'
export type {
  LanguageAdapter,
  LanguageAdapterCapabilities,
  LanguageAdapterInput,
  LanguageAdapterResult,
} from './schema/analysis'
export type {
  AnalysisFact,
  ProjectFacetDefinition,
  ProjectPlugin,
  ProjectPluginDetectInput,
  ProjectPluginDetection,
  ProjectPluginInput,
  ProjectPluginResult,
} from './schema/projectPlugin'
export type {
  CodebaseDirectory,
  CodebaseEntry,
  CodebaseEntryKind,
  CodebaseFile,
  CodebaseSnapshot,
  DirectoryNode,
  FileContentOmittedReason,
  FileNode,
  GraphEdge,
  GraphEdgeKind,
  NodeTag,
  NodeTagId,
  ProjectNode,
  ProjectSnapshot,
  ReadProjectSnapshotOptions,
  SourceLocation,
  SourceRange,
  SymbolKind,
  SymbolNode,
  SymbolVisibility,
} from './schema/snapshot'
export type {
  GraphLayerKey,
  GraphLayerVisibility,
  UiPreferences,
  VisualizerStore,
  VisualizerStoreActions,
  VisualizerStoreState,
  WorkingSetState,
  WorkspaceUiState,
} from './schema/store'
export type {
  CanvasBaseScene,
  CompareOverlaySourceType,
  LayoutCompareOverlayReference,
  OverlayFocusMode,
} from './schema/scene'
export type {
  InspectorTab,
  LayoutAnnotation,
  LayoutGroup,
  LayoutLane,
  LayoutNodeScope,
  LayoutNodePlacement,
  LayoutSpec,
  LayoutStrategyKind,
  SelectionState,
  VisualizerViewMode,
  ViewportState,
} from './schema/layout'
export type {
  AgentBrokerCompleteRequest,
  AgentActiveToolsRequest,
  AgentCodexImportResponse,
  AgentBrokerCallbackResult,
  AgentCompactionRequest,
  AgentControlsResponse,
  AgentBrokerLoginStartResponse,
  AgentModelSelectionRequest,
  AgentBrokerSessionResponse,
  AgentResumeSessionRequest,
  AgentSessionListResponse,
  AgentThinkingLevelRequest,
  AutonomousRunDetailResponse,
  AutonomousRunStartPayload,
  AutonomousRunStartResponse,
  AutonomousRunStopResponse,
  AutonomousRunTimelineResponse,
  AutonomousRunsResponse,
  AgentPromptRequest,
  PreprocessingEmbeddingRequest,
  PreprocessingEmbeddingResponse,
  PreprocessingContextResponse,
  PreprocessingSummaryRequest,
  PreprocessingSummaryResponse,
  PreprocessingContextUpdateRequest,
  AgentSettingsResponse,
  AgentSettingsUpdateRequest,
  AgentStateResponse,
  GitFileDiff,
  GitFileDiffLineChange,
  GitFileDiffResponse,
  UiPreferencesResponse,
  UiPreferencesUpdateRequest,
  AnalysisState,
  AnalysisStatus,
  DraftMutationResponse,
  GroupPrototypeCacheResponse,
  GroupPrototypeCacheUpdateRequest,
  GraphNeighborsResponse,
  LayoutListResponse,
  LayoutStateResponse,
  LayoutSummary,
  SemanticLayoutResponse,
  LayoutSuggestionPayload,
  LayoutSuggestionResponse,
  SnapshotResponse,
  TelemetryActivityResponse,
  TelemetryHeatmapRequest,
  TelemetryHeatmapResponse,
  TelemetryOverviewResponse,
  WorkspaceHistoryResponse,
  WorkspaceSyncStatusResponse,
} from './schema/api'
export type {
  HybridLayoutAnchor,
  HybridLayoutGroup,
  HybridLayoutLane,
  HybridLayoutProposal,
  LayoutArrangementMode,
  LayoutArrangementSortKey,
  LayoutArrangementSpacing,
  LayoutQueryEdgeRef,
  LayoutQueryNodeRef,
  LayoutQueryStats,
  LayoutSelector,
  LayoutSuggestionExecutionPath,
  LayoutSuggestionRequest,
} from './schema/layoutSuggestion'
export type {
  LayoutDraft,
  LayoutDraftSource,
  LayoutDraftStatus,
  LayoutPlanner,
  LayoutPlannerConstraints,
  LayoutPlannerContext,
  LayoutPlannerPlacement,
  LayoutPlannerProposal,
  LayoutPlannerProposalEnvelope,
  LayoutPlannerRequest,
  PlannerCoordinateSpace,
  PlannerEdgeRef,
  PlannerExistingLayout,
  PlannerExistingLayoutSummary,
  PlannerNodeRef,
  PlannerSnapshotMeta,
  ValidationIssue,
  ValidationIssueCode,
  ValidationIssueSeverity,
  ValidationResult,
} from './schema/planner'
export type {
  AgentHeatSample,
  TelemetryActivityEvent,
  TelemetryConfidence,
  TelemetryMode,
  TelemetryOverview,
  TelemetryOverviewBucket,
  TelemetrySource,
  TelemetryWindow,
} from './schema/telemetry'
export type {
  DirtyFileEditSignal,
  FollowCameraCommand,
  FollowControllerAction,
  FollowControllerContext,
  FollowControllerState,
  FollowControllerView,
  FollowDebugState,
  FollowDomainEvent,
  FollowInspectorCommand,
  FollowIntent,
  FollowRefreshStatus,
  FollowRefreshCommand,
  FollowTarget,
  FollowTargetConfidence,
  FollowTargetKind,
} from './app/follow'
export type {
  SemanticCacheManifest,
  SemanticCacheSnapshot,
  SemanticEmbeddingProvider,
  SemanticEmbeddingProviderKind,
  SemanticEmbeddingVectorRecord,
  GroupPrototypeCacheSnapshot,
  SemanticIndexState,
  SemanticLayoutBuildResult,
  SemanticPurposeSummaryRecord,
  SemanticProjectionPoint,
  SemanticProjectionRecord,
  SemanticRefinementInput,
  SemanticSymbolTextRecord,
  SemanticUmapInput,
} from './semantic/types'
export type {
  PreprocessedWorkspaceContext,
  PreprocessingProgress,
  PreprocessingRunState,
  PreprocessingStatus,
  PreprocessingResult,
  ArtifactSyncState,
  GitWorkspaceStatus,
  LayoutArtifactSyncStatus,
  SymbolArtifactSyncStatus,
  WorkspaceArtifactSyncStatus,
  WorkspaceProfile,
} from './preprocessing/types'
export {
  DEFAULT_PROJECT_TAGS,
  PROJECT_SNAPSHOT_SCHEMA_VERSION,
  isDirectoryNode,
  isFileNode,
  isSymbolNode,
} from './schema/snapshot'
export {
  DEFAULT_SELECTION_STATE,
  DEFAULT_VIEWPORT_STATE,
} from './schema/layout'
export { DEFAULT_GRAPH_LAYER_VISIBILITY } from './schema/store'
export { DEFAULT_LAYOUT_PLANNER_CONSTRAINTS } from './schema/planner'
export {
  buildSemanticSymbolText,
  buildSemanticSymbolTextRecord,
  buildSemanticSymbolTextRecords,
  hashSemanticText,
} from './semantic/symbolText'
export {
  buildSemanticPurposeSummaryPrompt,
  buildSemanticPurposeSummaryRecord,
  buildSemanticPurposeSummaryRecords,
} from './semantic/purposeSummaries'
export { preprocessWorkspaceSnapshot } from './preprocessing/preprocessingService'
export { analyzeWorkspaceArtifactSync } from './preprocessing/workspaceSync'
export {
  buildSemanticLayout,
  buildSemanticLayoutFromProjection,
  collectSemanticSymbolTexts,
} from './semantic/semanticLayout'
export {
  createEmptySemanticCacheSnapshot,
  createSemanticCacheManifest,
  mergeSemanticCacheSnapshot,
  SEMANTIC_CACHE_VERSION,
} from './semantic/semanticCache'
export { createSemanticEmbeddingProvider } from './semantic/embeddings/provider'
export {
  createLocalSemanticEmbeddingProvider,
  type LocalSemanticEmbeddingProviderOptions,
  embedTextsLocally,
} from './semantic/embeddings/localEmbeddingProvider'
export { embedTextsWithTfidf } from './semantic/embeddings/tfidfEmbeddingProvider'
export { projectSemanticEmbeddings } from './semantic/projection/umap'
export { refineSemanticLayout } from './semantic/projection/refinement'
